### ISSUE TITLE
frontend twig

### ISSUE THREAD

**Issue by MDRefiner** [angelodmrch/catalog#1]
Hi,

can you please explain how to display the category-list and products on the frontend?

This is what i tried but nothing gets shown:

```
{% for category in categories %}
<h1>{{ category.name }}</h1>
{% endfor %}
```

Thank you*

**Comment by angelodmrch** [comment]
Hi. Using the component funcion "getAll" should work.
Something like this
```
{% for category in categories.getAll %}
<h1>{{ category.name }}</h1>
{% endfor %}
```
